steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder:v1', '--publish', 'gcr.io/qwiklabs-gcp-02-c167985ff80f/cloudbowl-samples-dotnet:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/qwiklabs-gcp-02-c167985ff80f/cloudbowl-samples-dotnet:$COMMIT_SHA', '--platform=managed', '--project=qwiklabs-gcp-02-c167985ff80f', '--region=us-central1', '--allow-unauthenticated', '--memory=256Mi', 'cloudbowl-samples-dotnet']
