steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder:v1', '--publish', 'gcr.io/qwiklabs-gcp-03-5ce669b9b336/cloudbowl-samples-dotnet:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/qwiklabs-gcp-03-5ce669b9b336/cloudbowl-samples-dotnet:$COMMIT_SHA', '--platform=managed', '--project=qwiklabs-gcp-03-5ce669b9b336', '--region=us-central1', '--allow-unauthenticated', '--memory=256Mi', 'cloudbowl-samples-dotnet']
